AWSTemplateFormatVersion: '2010-09-09'
Description: Launch a t2.micro EC2 instance without a key pair

Resources:
  EC2InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and ICMP (ping)
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (update if needed for your region)
      SecurityGroups:
        - !Ref EC2InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: CFN-EC2-NoKeyPair
